// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raitongorganicsfarm.app.mb.entity;

import com.raitongorganicsfarm.app.mb.entity.SubscriberDataOnDemand;
import com.raitongorganicsfarm.app.mb.entity.SubscriberIntegrationTest;
import com.raitongorganicsfarm.app.mb.repository.SubscriberRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect SubscriberIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SubscriberIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SubscriberIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private SubscriberDataOnDemand SubscriberIntegrationTest.dod;
    
    @Autowired
    SubscriberRepository SubscriberIntegrationTest.subscriberRepository;
    
    @Test
    public void SubscriberIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        long count = subscriberRepository.count();
        Assert.assertTrue("Counter for 'Subscriber' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SubscriberIntegrationTest.testFind() {
        Subscriber obj = dod.getRandomSubscriber();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide an identifier", id);
        obj = subscriberRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Subscriber' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Subscriber' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SubscriberIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        long count = subscriberRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Subscriber', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Subscriber> result = subscriberRepository.findAll();
        Assert.assertNotNull("Find all method for 'Subscriber' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Subscriber' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SubscriberIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        long count = subscriberRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Subscriber> result = subscriberRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Subscriber' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Subscriber' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SubscriberIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", dod.getRandomSubscriber());
        Subscriber obj = dod.getNewTransientSubscriber(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Subscriber' identifier to be null", obj.getId());
        subscriberRepository.save(obj);
        Assert.assertNotNull("Expected 'Subscriber' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SubscriberIntegrationTest.testDelete() {
        Subscriber obj = dod.getRandomSubscriber();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to initialize correctly", obj);
        String id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Subscriber' failed to provide an identifier", id);
        obj = subscriberRepository.findOne(id);
        subscriberRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Subscriber' with identifier '" + id + "'", subscriberRepository.findOne(id));
    }
    
}
