// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raitongorganicsfarm.app.mb.entity;

import com.raitongorganicsfarm.app.mb.entity.SubscriberIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SubscriberIntegrationTest_Roo_Configurable {
    
    declare @type: SubscriberIntegrationTest: @Configurable;
    
}
