// Generated by CoffeeScript 1.3.3
'use strict';

var Subscriber;

Subscriber = function(subscriber) {
  this.gender = 'MALE';
  this.getReadableGender = function() {
    if (this.gender === 'MALE') {
      return 'Male';
    } else if (this.gender === 'FEMALE') {
      return 'Female';
    } else if (this.gender === 'NOT_SPECIFIC') {
      return 'Not Specific';
    } else {
      throw 'Invalid gender';
    }
  };
  this.isGenderActive = function(gender) {
    if (this.gender === gender) {
      return 'active btn-primary';
    } else {
      return void 0;
    }
  };
  $.extend(true, this, subscriber || {});
};
