// Generated by CoffeeScript 1.3.3
'use strict';

var s;

s = angular.module('raitong.mb.service', ['ngResource']);

s.factory('SubscriberService', function($resource) {
  var actions, url;
  url = 'subscribers/:customerNo';
  actions = {
    get: {
      method: 'GET',
      params: {
        id: '@customerNo'
      }
    }
  };
  return $resource(url, {}, actions);
});
