// Generated by CoffeeScript 1.3.3
'use strict';

var s;

s = angular.module('raitong.mb.service', ['ngResource']);

s.factory('SubscriberService', function($resource) {
  var actions, url;
  url = 'subscribers/:customerNo';
  actions = {
    get: {
      method: 'GET',
      params: {
        customerNo: '@customerNo'
      }
    },
    update: {
      method: 'POST',
      params: {
        customerNo: '@customerNo'
      }
    }
  };
  return $resource(url, {}, actions);
});

s.factory('SubscriptionService', function($resource) {
  var actions, url;
  url = 'subscribers/:customerNo/subscriptions/:subscriptionId';
  actions = {
    create: {
      method: 'POST'
    }
  };
  return $resource(url, {}, actions);
});
