// Generated by CoffeeScript 1.3.3
'use strict';

var CreateSubscriptionCtrl;

CreateSubscriptionCtrl = function($scope, $location, $routeParams, SubscriberService, SubscriptionService) {
  var subscriber;
  $scope.fromYear = moment().year() - 1;
  $scope.toYear = moment().year() + 4;
  subscriber = SubscriberService.get($routeParams, function() {
    return $scope.subscriber = new Subscriber(subscriber);
  });
  $scope.subscription = new Subscription;
  return $scope.createSubscription = function(s) {
    var customerNo, _subscription;
    customerNo = $routeParams.customerNo;
    return _subscription = SubscriptionService.create({
      customerNo: customerNo
    }, s, function() {
      $scope.subscription = _subscription;
      return $location.path("/subscribers/" + $scope.subscriber.customerNo);
    });
  };
};

CreateSubscriptionCtrl.$inject = ['$scope', '$location', '$routeParams', 'SubscriberService', 'SubscriptionService'];
