// Generated by CoffeeScript 1.3.3
'use strict';

var CreateSubscriptionCtrl;

CreateSubscriptionCtrl = function($scope, $routeParams, SubscriberService) {
  var subscriber;
  return subscriber = SubscriberService.get($routeParams, function() {
    return $scope.subscriber = new Subscriber(subscriber);
  });
};

CreateSubscriptionCtrl.$inject = ['$scope', '$routeParams', 'SubscriberService'];
