// Generated by CoffeeScript 1.3.3
'use strict';

var CreateSubscriberCtrl, ListSubscriberCtrl, SubscriberInfoCtrl;

ListSubscriberCtrl = function($http, $scope) {
  var getSubscribers;
  getSubscribers = function() {
    var req;
    req = $http.get('subscribers');
    req.success(function(subscribers) {
      return $scope.subscribers = subscribers;
    });
  };
  getSubscribers();
  $scope.del = function(s) {
    var req;
    req = $http["delete"]('subscribers/' + s.customerNo);
    req.success(function() {
      getSubscribers();
    });
  };
};

ListSubscriberCtrl.$inject = ['$http', '$scope'];

CreateSubscriberCtrl = function($scope, $http, $location) {
  $scope.wizard = {
    validations: ['basicInfoForm.$valid', 'contactInfoForm.$valid', 'otherInfoForm.$valid']
  };
  $scope.subscriber = {
    gender: 'MALE',
    getReadableGender: function() {
      if (this.gender === 'MALE') {
        return 'Male';
      } else if (this.gender === 'FEMALE') {
        return 'Female';
      } else if (this.gender === 'NOT_SPECIFIC') {
        return 'Not Specific';
      } else {
        throw 'Invalid gender';
      }
    },
    isGenderActive: function(gender) {
      if (this.gender === gender) {
        return 'active btn-primary';
      } else {
        return void 0;
      }
    }
  };
  $scope.dateOptions = [
    {
      'value': 1
    }
  ];
  $scope.setGender = function(gender, subscriber) {
    return subscriber.gender = gender;
  };
  return $scope.create = function(s) {
    var req;
    req = $http.post('subscribers', s);
    return req.success(function(subscriber) {
      $location.path('/subscribers');
    });
  };
};

CreateSubscriberCtrl.$inject = ['$scope', '$http', '$location'];

SubscriberInfoCtrl = function($scope, $http, $routeParams, SubscriberService) {
  var subscriber;
  subscriber = SubscriberService.get($routeParams, function() {
    $scope.subscriber = subscriber;
  });
};

SubscriberInfoCtrl.$inject = ['$scope', '$http', '$routeParams', 'SubscriberService'];
